#!/usr/bin/env bash
set -euo pipefail

# Writes frontend/runtime-config.js for the manual deployment flow.

if [[ $# -lt 1 ]]; then
  echo "Usage: scripts/write_frontend_config.sh https://your-query-lambda-url.lambda-url.<region>.on.aws/"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
API_ENDPOINT="$1"

cat > "${REPO_ROOT}/frontend/runtime-config.js" <<EOF
// Generated by scripts/write_frontend_config.sh
window.RAG_CONFIG = {
  apiEndpoint: "${API_ENDPOINT}"
};
EOF

echo "Wrote ${REPO_ROOT}/frontend/runtime-config.js"
